sudo: false
langage: python
cache: pip
python:
- 2.7
install:
- pip install -r requirements.txt --user
script:
- pytest --cov sqlcollection/
before_deploy: pip install twine --user
deploy:
  provider: pypi
  user: sqlcollection
  edge:
    branch: v1.8.45
  password:
    secure: WrJ6NmxzY3D3Smvf52s/I6z1gA7eZ2/4N82CCFuRyVBYfkOMtmry24dYYXC4Zuf/f+QzmTs77NsNm4Z224gOBRKsXdDPOEghp3nE+d1otf1m+aBk0GMrZWHiKJOZrYlmc4COIrLWJ1LTScL95chqPDBLFvkSe1l7aQdOT+FMFP02ZwJnVnjScPbnGuRddnXeXDvzPfl5aMGxZkQqRqSxQzut4ADVUqIHk4LvuJsZZ/wmio3AG2Ohb5mk9AY1Y3u/q+/8T9scD9Syr2EOOXD+7dRLGiRQ4kN/4WGjTMYJI6jsICz0798czJ5sGPzToYyo9BzxIPQIScaqQDQ4Gl1gt09nzlcVrOq3a0tOrR6j9/gL0ADzOGYPK3UK4xwm08gkfETlCb4be75FbaxkC7m5c1hYzVUvO6UGcJOyEYkpFmMh6h7+4KNcHQsaJ4RWEvHTv4BRSea+mxkvUKtLTRjBU0zfBJPJpmQcbm925Q2gjWXEQoy0GXoiYqlaTJhvkBRHJN+qqnOEOyO1XtaYwtYa1AOJyRfzORli1q/Vb9j158OEExZJvITltqm+No3EC31dcbEdhCPVpfE6SiEaIhxAoNkR5HTzHE0g1JIZ1cKfDhPQt5h6B5hYOec8o1EC3WX8RwRFkg1y/89Ia9V6Ijhbfo3NwvAFyc4ew4cwEtYik0w=
  on:
    branch: master
    tags: false
